### ISSUE TITLE
application-context.xml

### ISSUE THREAD

**Issue by misawsneto** [zarinfam/play24-guice-spring#1]
Hi, 

Thanks for sharing this awesome integration. I was wondering in which directory would I put the application-context.xml and other spring related configuration files? Also, I want to use spring data JPA/mongo/elasticsearch and configure these libs via application-context.xml. Is it possible? How?

congrats on this awesome integration.

**Comment by archie-sh** [comment]
In line 47 of the SpringModule you can declare an applicationcontext that loads the xml for you. I would recommend to use an AnnotationConfigApplicationContext instead of xml files.

**Comment by misawsneto** [comment]
Right! Thanks.
