### ISSUE TITLE
Mixing @Autowired and @Inject

### ISSUE THREAD

**Issue by FrEaKmAn** [zarinfam/play24-guice-spring#2]
Checking your service https://github.com/zarinfam/play24-guice-spring/blob/master/app/services/TestServiceImpl.java I noticed you are using @Autowired. I tried with @Inject but I got an error.

Doesn't Spring also support @Inject? or must I enable something extra?

**Comment by zarinfam** [comment]
For this purpose you have to add JSR 330 dependency to this project 

```
"javax.inject" % "javax.inject" % "1",
```

For more information see [this project](https://github.com/zarinfam/play-java-spring-jpa-rest).

**Comment by FrEaKmAn** [comment]
Great, it works.
